In [1]:
import tensorflow.keras as keras
import tensorflow as tf
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import pandas as pd

In [2]:
import cv2
import os
from tqdm import tqdm

In [3]:
DATADIR = "PetImages"

In [4]:

training_data=[]
Categories = ["Dog","Cat"]
IMG_SIZE=70
def train_data():
    for category in Categories:
        path=os.path.join(DATADIR,category)
        class_num=Categories.index(category)
        for img in tqdm(os.listdir(path)):
            try:
                img_array=cv2.imread(os.path.join(path,img),cv2.IMREAD_GRAYSCALE)
                img_array=cv2.resize(img_array,(IMG_SIZE,IMG_SIZE))
                training_data.append([img_array,class_num])
            except Exception as e:
                pass
    print(len(training_data))
    
train_data()
print(len(training_data))

100%|██████████| 12485/12485 [03:07<00:00, 66.61it/s]

24914
24914


In [5]:
import random

In [8]:
#import random

In [6]:
random.shuffle(training_data)

In [7]:
X=[]
y=[]
for features,lables in training_data:
    X.append(features)
    y.append(lables)
X= np.array(X).reshape(-1,IMG_SIZE,IMG_SIZE,1)

In [8]:
print(X[0])

[[[170]
  [170]
  [174]
  ...
  [153]
  [160]
  [148]]

 [[142]
  [143]
  [126]
  ...
  [144]
  [144]
  [139]]

 [[121]
  [110]
  [117]
  ...
  [126]
  [129]
  [123]]

 ...

 [[ 83]
  [138]
  [ 75]
  ...
  [111]
  [183]
  [142]]

 [[ 89]
  [ 82]
  [137]
  ...
  [241]
  [160]
  [149]]

 [[168]
  [169]
  [105]
  ...
  [159]
  [139]
  [156]]]


In [9]:
import pickle

In [10]:
pickle_out=open("X.pickle","wb")
pickle.dump(X,pickle_out)
pickle_out.close()
pickle_out=open("y.pickle","wb")
pickle.dump(y,pickle_out)
pickle_out.close()